server:
  servlet:
    context-path: /api/library

spring:
  application:
    name: icebooking

  datasource:
    url: jdbc:mysql://localhost:3306/bookbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    password: amizoneng1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ngouoleonel3@gmail.com
    password: wlax zthp fymp nfoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000/eureka}
  instance:
    preferIpAddress: true
